name: FTP Upload

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /  # Upload all files from the root of the repository
          server-dir: public_html/wp-content/themes/codexlab-theme  # Path on FTP server where files should be uploaded
          protocol: ftps  # Using FTPS for secure file transfer
