name: FTP Upload

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ftpignore
        run: |
          echo "/lost+found" > .ftpignore
          echo "/.github" >> .ftpignore
          echo "/node_modules" >> .ftpignore

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp://vetoent.com:21
          username: u763604430.scalelabz.com
          password: RECY4CgAL$ZGc.C
          local-dir: ./
          server-dir: /public_html/wp-content/themes/codexlab-theme/
          protocol: ftp
          port: 21
